language: node_js # don't install any environment

node_js:
  - "lts/*"

script:
  - npm run build -- --prod

deploy:
  provider: script
  skip-cleanup: true
  script: bash deploy/deploy.sh
  on:
    branch: master
