name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - name: Lint
        run: |
          npm install
          npm run lint
